In [59]:
import pandas as pd
import numpy as np
from collections import defaultdict
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer
import matplotlib.pyplot as plt
import seaborn as sns

# Для отображения графиков в ноутбуке
%matplotlib inline

Датасет возьмем снова KION: https://github.com/irsafilo/KION_DATASET/

In [60]:
items = pd.read_csv('../../items.csv')
items.head(1)

,item_id,content_type,title,title_orig,release_year,genres,countries,for_kids,age_rating,studios,directors,actors,description,keywords
0,10711,film,Поговори с ней,Hable con ella,2002.0,"драмы, зарубежные, детективы, мелодрамы",Испания,NaN,16.0,NaN,Педро Альмодовар,"Адольфо Фернандес, Ана Фернандес, Дарио Гранди...",Мелодрама легендарного Педро Альмодовара «Пого...,"Поговори, ней, 2002, Испания, друзья, любовь, ..."

In [62]:
df = pd.read_csv('../../interactions.csv')
df.head()

   user_id  item_id last_watch_dt  total_dur  watched_pct
0   176549     9506    2021-05-11     4250.0         72.0
1   699317     1659    2021-05-29     8317.0        100.0
2   656683     7107    2021-05-09       10.0          0.0
3   864613     7638    2021-07-05    14483.0        100.0
4   964868     9506    2021-04-30     6725.0        100.0

In [63]:
most_pop_recs = df.item_id.value_counts()[:10].index.values.tolist()
most_pop_recs

[10440, 15297, 9728, 13865, 4151, 3734, 2657, 4880, 142, 6809]

In [66]:
random_recs = df.item_id.sample(n=10).values.tolist()
random_recs

[16289, 14942, 14051, 9359, 8922, 12360, 2942, 15297, 3411, 9927]

In [67]:
novel_recs = df.item_id.value_counts()[-10:].index.values.tolist()
novel_recs

[11315, 9467, 11704, 14528, 1254, 1506, 6512, 5332, 4109, 11091]

In [68]:
test_users = df.user_id.sample(n=1000).reset_index()
test_users['index'] = 1

most_pop_recs = pd.DataFrame(most_pop_recs, columns=['item_id'])
random_recs = pd.DataFrame(random_recs, columns=['item_id'])
novel_recs = pd.DataFrame(novel_recs, columns=['item_id'])

most_pop_recs['index'] = 1
random_recs['index'] = 1
novel_recs['index'] = 1

most_pop_data = test_users.merge(most_pop_recs).drop(['index'], axis=1)
random_data = test_users.merge(random_recs).drop(['index'], axis=1)
novel_recs_data = test_users.merge(novel_recs).drop(['index'], axis=1)

In [69]:
most_pop_data.head()

   user_id  item_id
0   333829    10440
1   333829    15297
2   333829     9728
3   333829    13865
4   333829     4151

In [70]:
random_data['item_id'] = df.item_id.sample(n=random_data.shape[0], replace=True).values
random_data.head()

   user_id  item_id
0   333829     6384
1   333829    15297
2   333829    11605
3   333829    12118
4   333829    10440

In [71]:
novel_recs_data.head()

   user_id  item_id
0   333829    11315
1   333829     9467
2   333829    11704
3   333829    14528
4   333829     1254

## Новизна

Novelty измеряет, насколько новые/непопулярные товары рекомендуются пользователям.

In [72]:
# Рассчитаем популярность каждого товара (сколько пользователей его смотрели)
item_popularity = df.groupby('item_id')['user_id'].nunique().reset_index()
item_popularity.columns = ['item_id', 'num_users']

# Функция для расчета novelty рекомендаций
def calculate_novelty(recommendations, item_popularity):
    """
    recommendations - DataFrame с колонками: user_id, item_id
    item_popularity - DataFrame с колонками: item_id, num_users
    """
    rec_with_pop = pd.merge(recommendations, item_popularity, on='item_id', how='left')
    total_users = recommendations['user_id'].nunique()
    novelty = -np.log(rec_with_pop['num_users'] / total_users).mean()
    return novelty


for x in [most_pop_data, random_data, novel_recs_data]:
    novelty_score = calculate_novelty(x, item_popularity)
    print(f"Novelty score: {novelty_score:.4f}")

Novelty score: -3.2509
Novelty score: -0.3014
Novelty score: 6.9058

## Покрытие (coverage)

In [73]:
def calculate_catalog_coverage(recommendations, catalog_size):
    """
    recommendations - DataFrame с колонками: user_id, item_id
    catalog_size - общее количество товаров в каталоге
    """
    unique_recommended_items = recommendations['item_id'].nunique()
    coverage = unique_recommended_items / catalog_size
    return coverage

# Пример использования
catalog_size = df['item_id'].nunique()  # в реальности может быть больше

for x in [most_pop_data, random_data, novel_recs_data]:
    coverage_score = calculate_catalog_coverage(x, catalog_size)
    print(f"Catalog coverage: {coverage_score:.2%}")

Catalog coverage: 0.08%
Catalog coverage: 20.48%
Catalog coverage: 0.08%

## Разнообразие

In [74]:
from tqdm import tqdm

item_sim_flag = {}
for row1 in tqdm(items.itertuples()):
    for row2 in items[row1.Index:].itertuples():
        if row1.item_id != row2.item_id:
            if row1.genres == row2.genres:
                item_sim_flag[(row1.item_id, row2.item_id)] = 1

15963it [01:32, 171.67it/s]

In [46]:
item_sim_flag

{(10711, 9182): 1,
 (10711, 15851): 1,
 (10711, 9224): 1,
 (10711, 14509): 1,
 (2508, 1245): 1,
 (2508, 7131): 1,
 (2508, 16507): 1,
 (2508, 12576): 1,
 (2508, 12665): 1,
 (2508, 15288): 1,
 (2508, 16481): 1,
 (2508, 3311): 1,
 (2508, 2503): 1,
 (2508, 10478): 1,
 (2508, 13637): 1,
 (2508, 8004): 1,
 (10716, 5097): 1,
 (10716, 4900): 1,
 (10716, 7945): 1,
 (10716, 888): 1,
 (10716, 3797): 1,
 (10716, 8395): 1,
 (7868, 13729): 1,
 (7868, 6521): 1,
 (7868, 10460): 1,
 (7868, 12445): 1,
 (7868, 9177): 1,
 (7868, 9971): 1,
 (7868, 5548): 1,
 (7868, 16206): 1,
 (7868, 5707): 1,
 (7868, 168): 1,
 (7868, 1806): 1,
 (7868, 555): 1,
 (7868, 6480): 1,
 (7868, 5368): 1,
 (7868, 6490): 1,
 (7868, 4170): 1,
 (7868, 15869): 1,
 (7868, 6616): 1,
 (7868, 3997): 1,
 (7868, 5478): 1,
 (7868, 5001): 1,
 (7868, 14092): 1,
 (7868, 15990): 1,
 (7868, 11299): 1,
 (7868, 15539): 1,
 (7868, 5480): 1,
 (7868, 14650): 1,
 (7868, 16404): 1,
 (7868, 4325): 1,
 (7868, 2169): 1,
 (7868, 7423): 1,
 (7868, 2067): 1,
 (7868, 2742): 1,
 (7868, 5846): 1,
 (7868, 1008): 1,
 (7868, 11558): 1,
 (7868, 4388): 1,
 (7868, 15927): 1,
 (7868, 3304): 1,
 (7868, 14519): 1,
 (7868, 8800): 1,
 (7868, 15788): 1,
 (7868, 8889): 1,
 (7868, 4502): 1,
 (7868, 11669): 1,
 (7868, 11292): 1,
 (7868, 8050): 1,
 (7868, 15912): 1,
 (7868, 14665): 1,
 (7868, 940): 1,
 (7868, 9187): 1,
 (7868, 15984): 1,
 (7868, 1156): 1,
 (7868, 15567): 1,
 (7868, 12390): 1,
 (7868, 403): 1,
 (7868, 3793): 1,
 (7868, 14681): 1,
 (7868, 14649): 1,
 (7868, 471): 1,
 (7868, 4868): 1,
 (7868, 6943): 1,
 (7868, 13222): 1,
 (7868, 15157): 1,
 (7868, 11815): 1,
 (7868, 9753): 1,
 (7868, 261): 1,
 (7868, 9661): 1,
 (7868, 3752): 1,
 (7868, 15252): 1,
 (7868, 11726): 1,
 (7868, 3897): 1,
 (7868, 15240): 1,
 (7868, 12810): 1,
 (7868, 3705): 1,
 (7868, 12669): 1,
 (7868, 5457): 1,
 (7868, 94): 1,
 (7868, 15594): 1,
 (7868, 12581): 1,
 (7868, 8873): 1,
 (7868, 4705): 1,
 (7868, 11251): 1,
 (7868, 1441): 1,
 (7868, 16109): 1,
 (7868, 6503): 1,
 (7868, 12054): 1,
 (7868, 2713): 1,
 (7868, 479): 1,
 (854, 7325): 1,
 (854, 5845): 1,
 (854, 6232): 1,
 (854, 16354): 1,
 (854, 14411): 1,
 (854, 8640): 1,
 (854, 1914): 1,
 (854, 7340): 1,
 (854, 11281): 1,
 (854, 9022): 1,
 (854, 12468): 1,
 (854, 4437): 1,
 (854, 3926): 1,
 (854, 10864): 1,
 (854, 16310): 1,
 (854, 8384): 1,
 (854, 7085): 1,
 (854, 16): 1,
 (854, 16254): 1,
 (854, 13366): 1,
 (854, 8280): 1,
 (854, 13346): 1,
 (854, 13997): 1,
 (854, 10131): 1,
 (854, 1701): 1,
 (854, 3273): 1,
 (854, 10413): 1,
 (854, 14707): 1,
 (854, 5013): 1,
 (854, 14289): 1,
 (854, 6961): 1,
 (854, 7454): 1,
 (854, 11169): 1,
 (854, 9155): 1,
 (854, 13116): 1,
 (854, 8994): 1,
 (854, 7974): 1,
 (854, 5342): 1,
 (854, 14103): 1,
 (854, 8055): 1,
 (854, 4701): 1,
 (854, 946): 1,
 (854, 5866): 1,
 (854, 8259): 1,
 (854, 5246): 1,
 (854, 222): 1,
 (854, 2949): 1,
 (854, 15614): 1,
 (854, 10993): 1,
 (854, 4680): 1,
 (854, 1688): 1,
 (854, 2551): 1,
 (854, 11466): 1,
 (854, 13914): 1,
 (854, 6014): 1,
 (854, 15030): 1,
 (854, 11009): 1,
 (854, 3964): 1,
 (854, 3736): 1,
 (854, 12818): 1,
 (854, 1654): 1,
 (854, 1488): 1,
 (854, 1011): 1,
 (854, 8719): 1,
 (854, 3641): 1,
 (854, 10206): 1,
 (854, 1410): 1,
 (854, 10920): 1,
 (854, 13619): 1,
 (854, 7070): 1,
 (854, 14521): 1,
 (854, 13533): 1,
 (854, 5981): 1,
 (854, 12899): 1,
 (854, 11942): 1,
 (854, 6223): 1,
 (854, 9356): 1,
 (854, 4634): 1,
 (854, 14291): 1,
 (854, 6088): 1,
 (854, 4064): 1,
 (854, 13858): 1,
 (854, 5966): 1,
 (854, 13614): 1,
 (854, 4391): 1,
 (854, 6129): 1,
 (854, 833): 1,
 (854, 2845): 1,
 (854, 8956): 1,
 (854, 3410): 1,
 (854, 4410): 1,
 (854, 11639): 1,
 (854, 13856): 1,
 (854, 12144): 1,
 (854, 13751): 1,
 (854, 15831): 1,
 (854, 14941): 1,
 (854, 3000): 1,
 (854, 16221): 1,
 (854, 12368): 1,
 (854, 2545): 1,
 (854, 16441): 1,
 (854, 647): 1,
 (854, 15978): 1,
 (854, 6350): 1,
 (854, 10462): 1,
 (854, 9442): 1,
 (854, 413): 1,
 (854, 14966): 1,
 (854, 15393): 1,
 (854, 10384): 1,
 (854, 16337): 1,
 (854, 13208): 1,
 (854, 15685): 1,
 (854, 4294): 1,
 (854, 4608): 1,
 (854, 225): 1,
 (854, 1289): 1,
 (854, 5009): 1,
 (854, 12143): 1,
 (854, 2188): 1,
 (854, 8661): 1,
 (854, 7388): 1,
 (854, 4019): 1,
 (854, 15502): 1,
 (854, 2325): 1,
 (854, 8935): 1,
 (854, 13026): 1,
 (854, 4205): 1,
 (854, 5440): 1,
 (854, 14724): 1,
 (854, 13049): 1,
 (854, 803): 1,
 (854, 4343): 1,
 (854, 13664): 1,
 (854, 800): 1,
 (854, 14830): 1,
 (854, 3199): 1,
 (854, 16030): 1,
 (854, 16204): 1,
 (854, 7837): 1,
 (854, 16137): 1,
 (854, 7376): 1,
 (854, 215): 1,
 (854, 5067): 1,
 (854, 5697): 1,
 (854, 10874): 1,
 (854, 10510): 1,
 (854, 5343): 1,
 (854, 14034): 1,
 (854, 12209): 1,
 (854, 2394): 1,
 (854, 4923): 1,
 (854, 8065): 1,
 (854, 6819): 1,
 (854, 11449): 1,
 (854, 412): 1,
 (854, 1560): 1,
 (854, 14968): 1,
 (9853, 5552): 1,
 (9853, 1384): 1,
 (9853, 1058): 1,
 (9853, 1919): 1,
 (9853, 2418): 1,
 (9853, 13507): 1,
 (9853, 14463): 1,
 (9853, 15225): 1,
 (9853, 10729): 1,
 (9853, 883): 1,
 (9853, 12009): 1,
 (9853, 13154): 1,
 (9853, 16474): 1,
 (9853, 7778): 1,
 (9853, 14137): 1,
 (9853, 16004): 1,
 (9853, 15160): 1,
 (9853, 2570): 1,
 (9853, 6321): 1,
 (9853, 1159): 1,
 (9853, 7843): 1,
 (9853, 7792): 1,
 (9853, 4604): 1,
 (9853, 13226): 1,
 (9853, 152): 1,
 (9853, 5371): 1,
 (9853, 5018): 1,
 (9853, 6621): 1,
 (9853, 6107): 1,
 (9853, 4744): 1,
 (9853, 3100): 1,
 (9853, 7316): 1,
 (9853, 14758): 1,
 (8604, 14986): 1,
 (8604, 8324): 1,
 (8604, 3762): 1,
 (8604, 10709): 1,
 (8604, 13607): 1,
 (8604, 6513): 1,
 (8604, 1457): 1,
 (8604, 8635): 1,
 (8604, 11937): 1,
 (8604, 374): 1,
 (8604, 6578): 1,
 (8604, 204): 1,
 (8604, 8944): 1,
 (8604, 14857): 1,
 (8604, 6535): 1,
 (8604, 2884): 1,
 (8604, 13790): 1,
 (8604, 8149): 1,
 (8604, 14520): 1,
 (8604, 4862): 1,
 (8604, 436): 1,
 (8604, 7666): 1,
 (8604, 4092): 1,
 (8604, 8808): 1,
 (8604, 7086): 1,
 (8604, 5407): 1,
 (8604, 16042): 1,
 (8604, 27): 1,
 (8604, 4854): 1,
 (8604, 8739): 1,
 (8604, 13408): 1,
 (8604, 5279): 1,
 (8604, 14855): 1,
 (8604, 13462): 1,
 (8604, 8547): 1,
 (8604, 5698): 1,
 (8604, 9597): 1,
 (8604, 13105): 1,
 (8604, 1363): 1,
 (8604, 5384): 1,
 (8604, 11981): 1,
 (8604, 1906): 1,
 (8604, 3642): 1,
 (8604, 16376): 1,
 (8604, 13316): 1,
 (8604, 10392): 1,
 (8604, 14647): 1,
 (8604, 5852): 1,
 (8604, 4412): 1,
 (8604, 11626): 1,
 (8604, 10481): 1,
 (8604, 10181): 1,
 (8604, 7167): 1,
 (8604, 12169): 1,
 (8604, 14629): 1,
 (8604, 10980): 1,
 (8604, 8190): 1,
 (8604, 10744): 1,
 (8604, 10347): 1,
 (8604, 5746): 1,
 (8604, 128): 1,
 (8604, 9312): 1,
 (8604, 7003): 1,
 (8604, 15273): 1,
 (8604, 7355): 1,
 (8604, 12616): 1,
 (8604, 9063): 1,
 (8604, 5184): 1,
 (8604, 11235): 1,
 (8604, 12755): 1,
 (8604, 6680): 1,
 (8604, 14501): 1,
 (8604, 14219): 1,
 (8604, 9020): 1,
 (8604, 8938): 1,
 (8604, 14768): 1,
 (8604, 1954): 1,
 (8604, 5233): 1,
 (8604, 9491): 1,
 (8604, 15532): 1,
 (8604, 10412): 1,
 (8604, 1005): 1,
 (8604, 467): 1,
 (8604, 9556): 1,
 (8604, 8804): 1,
 (8604, 16329): 1,
 (8604, 10399): 1,
 (8604, 5394): 1,
 (8604, 2903): 1,
 (8604, 14503): 1,
 (8604, 7228): 1,
 (8604, 11963): 1,
 (8604, 4521): 1,
 (8604, 3913): 1,
 (8604, 1182): 1,
 (8604, 2342): 1,
 (8604, 4300): 1,
 (8604, 1366): 1,
 (8604, 15824): 1,
 (8604, 7336): 1,
 (8604, 7037): 1,
 (8604, 14479): 1,
 (8604, 13082): 1,
 (8604, 4568): 1,
 (8604, 4752): 1,
 (8604, 10398): 1,
 (8604, 11234): 1,
 (8604, 9013): 1,
 (8604, 9925): 1,
 (8604, 4963): 1,
 (8604, 2919): 1,
 (8604, 4192): 1,
 (8604, 7675): 1,
 (8604, 12420): 1,
 (8604, 13801): 1,
 (8604, 16468): 1,
 (8604, 3765): 1,
 (8604, 14824): 1,
 (8604, 523): 1,
 (8604, 9686): 1,
 (8604, 332): 1,
 (8604, 1979): 1,
 (8604, 625): 1,
 (8604, 15125): 1,
 (8604, 5864): 1,
 (8604, 5901): 1,
 (8604, 16090): 1,
 (8604, 3111): 1,
 (8604, 14181): 1,
 (8604, 5365): 1,
 (8604, 11750): 1,
 (8604, 2978): 1,
 (8604, 3319): 1,
 (8604, 13420): 1,
 (8604, 4114): 1,
 (8604, 8669): 1,
 (8604, 11859): 1,
 (8604, 8913): 1,
 (8604, 8120): 1,
 (8604, 11584): 1,
 (8604, 6938): 1,
 (8604, 4427): 1,
 (8604, 12897): 1,
 (8604, 14102): 1,
 (8604, 381): 1,
 (8604, 7776): 1,
 (8604, 15860): 1,
 (8604, 2219): 1,
 (8604, 1511): 1,
 (8604, 7736): 1,
 (8604, 14947): 1,
 (8604, 9888): 1,
 (8604, 6263): 1,
 (8604, 2756): 1,
 (8604, 10578): 1,
 (8604, 12023): 1,
 (8604, 362): 1,
 (8604, 277): 1,
 (8604, 11533): 1,
 (8604, 15866): 1,
 (8604, 15079): 1,
 (8604, 4708): 1,
 (8604, 2267): 1,
 (8604, 2189): 1,
 (8604, 10873): 1,
 (8604, 1525): 1,
 (8604, 8158): 1,
 (8604, 5211): 1,
 (8604, 5860): 1,
 (8604, 1270): 1,
 (8604, 908): 1,
 (8604, 8277): 1,
 (8604, 11137): 1,
 (8604, 1722): 1,
 (8604, 5927): 1,
 (8604, 6304): 1,
 (8604, 150): 1,
 (8604, 10907): 1,
 (8604, 13182): 1,
 (8604, 8439): 1,
 (8604, 2536): 1,
 (8604, 3128): 1,
 (8604, 10221): 1,
 (8604, 15722): 1,
 (8604, 6498): 1,
 (8604, 6875): 1,
 (8604, 13596): 1,
 (8604, 6362): 1,
 (8604, 10597): 1,
 (8604, 7812): 1,
 (8604, 15842): 1,
 (8604, 16115): 1,
 (8604, 1924): 1,
 (8604, 16215): 1,
 (8604, 7552): 1,
 (8604, 15829): 1,
 (8604, 10064): 1,
 (8604, 6880): 1,
 (8604, 6727): 1,
 (8604, 8300): 1,
 (8604, 6475): 1,
 (8604, 15922): 1,
 (8604, 3690): 1,
 (8604, 7136): 1,
 (8604, 3725): 1,
 (8604, 9516): 1,
 (8604, 1401): 1,
 (8604, 7277): 1,
 (8604, 858): 1,
 (8604, 2450): 1,
 (8604, 1795): 1,
 (8604, 3041): 1,
 (8604, 11607): 1,
 (8604, 4307): 1,
 (8604, 2230): 1,
 (8604, 13050): 1,
 (8604, 8396): 1,
 (8604, 8073): 1,
 (8604, 7020): 1,
 (8604, 2482): 1,
 (8604, 8673): 1,
 (8604, 7159): 1,
 (8604, 11880): 1,
 (8604, 12351): 1,
 (8604, 15503): 1,
 (8604, 5736): 1,
 (8604, 12916): 1,
 (8604, 15944): 1,
 (8604, 6103): 1,
 (8604, 6532): 1,
 (8604, 15973): 1,
 (8604, 7038): 1,
 (8604, 662): 1,
 (8604, 10885): 1,
 (8604, 250): 1,
 (8604, 11867): 1,
 (8604, 2139): 1,
 (8604, 4695): 1,
 (8604, 13675): 1,
 (8604, 5999): 1,
 (8604, 11482): 1,
 (8604, 12433): 1,
 (8604, 7296): 1,
 (8604, 11278): 1,
 (8604, 6673): 1,
 (8604, 11926): 1,
 (8604, 14597): 1,
 (8604, 8028): 1,
 (8604, 12630): 1,
 (8604, 8774): 1,
 (8604, 3317): 1,
 (8604, 13975): 1,
 (8604, 6011): 1,
 (8604, 14371): 1,
 (8604, 14924): 1,
 (8604, 13961): 1,
 (8604, 6407): 1,
 (8604, 8079): 1,
 (8604, 5619): 1,
 (8604, 12233): 1,
 (8604, 14360): 1,
 (8604, 1089): 1,
 (8604, 6269): 1,
 (8604, 4688): 1,
 (8604, 7071): 1,
 (8604, 9502): 1,
 (8604, 190): 1,
 (8604, 10745): 1,
 (8604, 2877): 1,
 (8604, 13381): 1,
 (8604, 1430): 1,
 (8604, 12642): 1,
 (8604, 8375): 1,
 (8604, 12472): 1,
 (8604, 6679): 1,
 (8604, 2040): 1,
 (8604, 425): 1,
 (8604, 16245): 1,
 (8604, 3933): 1,
 (8604, 15887): 1,
 (8604, 13270): 1,
 (8604, 14333): 1,
 (8604, 3370): 1,
 (8604, 792): 1,
 (8604, 6884): 1,
 (8604, 14868): 1,
 (8604, 13860): 1,
 (8604, 3197): 1,
 (8604, 535): 1,
 (8604, 7732): 1,
 (8604, 10272): 1,
 (8604, 5088): 1,
 (8604, 16281): 1,
 (8604, 10803): 1,
 (8604, 15264): 1,
 (8604, 8756): 1,
 (8604, 217): 1,
 (8604, 11529): 1,
 (8604, 8195): 1,
 (8604, 8012): 1,
 (8604, 5406): 1,
 (8604, 12164): 1,
 (8604, 782): 1,
 (8604, 5221): 1,
 (8604, 11853): 1,
 (8604, 11051): 1,
 (8604, 16514): 1,
 (8604, 14474): 1,
 (8604, 6537): 1,
 (8604, 5874): 1,
 (8604, 431): 1,
 (8604, 6203): 1,
 (8604, 15957): 1,
 (8604, 3776): 1,
 (8604, 12795): 1,
 (8604, 7413): 1,
 (8604, 16388): 1,
 (8604, 16287): 1,
 (8604, 9839): 1,
 (8604, 12578): 1,
 (8604, 11167): 1,
 (8604, 14781): 1,
 (8604, 4262): 1,
 (8604, 39): 1,
 (8604, 3504): 1,
 (8604, 7696): 1,
 (8604, 14367): 1,
 (8604, 7040): 1,
 (8604, 336): 1,
 (8604, 14457): 1,
 (8604, 1374): 1,
 (8604, 6376): 1,
 (8604, 11566): 1,
 (8604, 14490): 1,
 (8604, 6850): 1,
 (8604, 7960): 1,
 (8604, 11820): 1,
 (8604, 2750): 1,
 (8604, 8413): 1,
 (8604, 7366): 1,
 (8604, 1134): 1,
 (8604, 1138): 1,
 (8604, 14875): 1,
 (8604, 10820): 1,
 (8604, 2577): 1,
 (8604, 8768): 1,
 (8604, 8115): 1,
 (8604, 9360): 1,
 (8604, 16451): 1,
 (8604, 1227): 1,
 (8604, 2747): 1,
 (8604, 2047): 1,
 (8604, 12218): 1,
 (8604, 1479): 1,
 (8604, 10877): 1,
 (8604, 12613): 1,
 (8604, 4520): 1,
 (8604, 9237): 1,
 (8604, 13830): 1,
 (8604, 16374): 1,
 (8604, 15012): 1,
 (8604, 11943): 1,
 (8604, 4037): 1,
 (8604, 631): 1,
 (8604, 9248): 1,
 (8604, 6575): 1,
 (8604, 12270): 1,
 (8604, 6338): 1,
 (8604, 1432): 1,
 (8604, 1231): 1,
 (8604, 9579): 1,
 (8604, 10863): 1,
 (8604, 6548): 1,
 (8604, 1017): 1,
 (8604, 9596): 1,
 (8604, 4764): 1,
 (8604, 15451): 1,
 (8604, 2964): 1,
 (8604, 3508): 1,
 (8604, 464): 1,
 (8604, 12345): 1,
 (8604, 11788): 1,
 (8604, 4837): 1,
 (8604, 2455): 1,
 (8604, 6494): 1,
 (8604, 1370): 1,
 (8604, 11542): 1,
 (8604, 12644): 1,
 (8604, 16496): 1,
 (8604, 4949): 1,
 (8604, 10782): 1,
 (8604, 7520): 1,
 (8604, 9049): 1,
 (8604, 7450): 1,
 (8604, 11108): 1,
 (8604, 11301): 1,
 (8604, 13028): 1,
 (8604, 13813): 1,
 (8604, 5078): 1,
 (8604, 8240): 1,
 (8604, 9407): 1,
 (8604, 9023): 1,
 (8604, 8097): 1,
 (8604, 10426): 1,
 (8604, 15167): 1,
 (8604, 1537): 1,
 (8604, 8975): 1,
 (8604, 12745): 1,
 (8604, 1352): 1,
 (8604, 13774): 1,
 (8604, 5484): 1,
 (8604, 2023): 1,
 (8604, 15552): 1,
 (8604, 3002): 1,
 (8604, 4430): 1,
 (15056, 3530): 1,
 (15056, 10388): 1,
 (15056, 4408): 1,
 (15056, 879): 1,
 (15056, 6496): 1,
 (15056, 4990): 1,
 (15056, 10451): 1,
 (15056, 14564): 1,
 (15056, 2706): 1,
 (15056, 15830): 1,
 (15056, 13670): 1,
 (15056, 3818): 1,
 (15056, 3290): 1,
 (15056, 4659): 1,
 (15056, 13469): 1,
 (15056, 9210): 1,
 (15056, 827): 1,
 (15056, 2240): 1,
 (15056, 11428): 1,
 (15056, 7283): 1,
 (15056, 12641): 1,
 (15056, 10095): 1,
 (15056, 6396): 1,
 (15056, 13841): 1,
 (15056, 3007): 1,
 (15056, 15407): 1,
 (15056, 10894): 1,
 (15056, 12617): 1,
 (15056, 11686): 1,
 (15056, 11632): 1,
 (15056, 1577): 1,
 (4778, 5891): 1,
 (4778, 14508): 1,
 (4778, 8920): 1,
 (6181, 10883): 1,
 (6181, 7901): 1,
 (6181, 10999): 1,
 (6181, 3036): 1,
 (6181, 7790): 1,
 (6181, 1586): 1,
 (6181, 2118): 1,
 (6181, 11667): 1,
 (6181, 15658): 1,
 (15076, 5900): 1,
 (15076, 2927): 1,
 (15076, 1010): 1,
 (15076, 16010): 1,
 (15076, 4631): 1,
 (15076, 1755): 1,
 (15076, 12248): 1,
 (15076, 10767): 1,
 (15076, 9107): 1,
 (15076, 7364): 1,
 (15076, 1380): 1,
 (15076, 12486): 1,
 (2904, 7501): 1,
 (2904, 12823): 1,
 (2904, 15700): 1,
 (2904, 10619): 1,
 (2904, 12072): 1,
 (2904, 13085): 1,
 (2904, 11841): 1,
 (6881, 15892): 1,
 (6881, 4208): 1,
 (14921, 1943): 1,
 (14921, 14198): 1,
 (14921, 16371): 1,
 (14921, 388): 1,
 (14921, 14653): 1,
 (14921, 8475): 1,
 (14921, 14332): 1,
 (14921, 7511): 1,
 (14921, 13829): 1,
 (14921, 16252): 1,
 (14921, 3375): 1,
 (14921, 5229): 1,
 (14921, 7911): 1,
 (14921, 7853): 1,
 (14921, 3688): 1,
 (14921, 9028): 1,
 (14921, 1900): 1,
 (14921, 15126): 1,
 (14921, 10822): 1,
 (14921, 12045): 1,
 (14921, 3414): 1,
 (14921, 163): 1,
 (14921, 3820): 1,
 (14921, 1958): 1,
 (14921, 4451): 1,
 (14921, 15117): 1,
 (14921, 13155): 1,
 (14921, 1214): 1,
 (14921, 8416): 1,
 (14921, 7321): 1,
 (14921, 11393): 1,
 (14921, 13142): 1,
 (14921, 2132): 1,
 (14921, 699): 1,
 (14921, 14471): 1,
 (14921, 5146): 1,
 (14921, 10097): 1,
 (14921, 16352): 1,
 (14921, 12347): 1,
 (14921, 14940): 1,
 (14921, 13009): 1,
 (14921, 6438): 1,
 (14921, 9328): 1,
 (14921, 8331): 1,
 (14921, 7972): 1,
 (14921, 9765): 1,
 (14921, 4144): 1,
 (14921, 5627): 1,
 (14921, 1771): 1,
 (14921, 14055): 1,
 (14921, 15943): 1,
 (14921, 5959): 1,
 (14921, 4392): 1,
 (14921, 7876): 1,
 (15261, 7443): 1,
 (15261, 14329): 1,
 (3445, 11195): 1,
 (3445, 13245): 1,
 (3445, 12110): 1,
 (3445, 7328): 1,
 (3445, 4748): 1,
 (3445, 806): 1,
 (3445, 5492): 1,
 (3445, 116): 1,
 (3445, 7163): 1,
 (3445, 3806): 1,
 (3445, 2885): 1,
 (3445, 10687): 1,
 (3445, 10810): 1,
 (3445, 9836): 1,
 (3445, 9674): 1,
 (3445, 9943): 1,
 (3445, 10057): 1,
 (3445, 9575): 1,
 (3445, 5433): 1,
 (3445, 3949): 1,
 (3445, 13834): 1,
 (3445, 16286): 1,
 (3445, 15360): 1,
 (3445, 13465): 1,
 (3445, 9268): 1,
 (3445, 15583): 1,
 (3445, 7740): 1,
 (3445, 9994): 1,
 (3445, 2436): 1,
 (3445, 7212): 1,
 (3445, 10668): 1,
 (3445, 453): 1,
 (13729, 6521): 1,
 (13729, 10460): 1,
 (13729, 12445): 1,
 (13729, 9177): 1,
 (13729, 9971): 1,
 (13729, 5548): 1,
 (13729, 16206): 1,
 (13729, 5707): 1,
 (13729, 168): 1,
 (13729, 1806): 1,
 (13729, 555): 1,
 (13729, 6480): 1,
 (13729, 5368): 1,
 (13729, 6490): 1,
 (13729, 4170): 1,
 (13729, 15869): 1,
 (13729, 6616): 1,
 (13729, 3997): 1,
 (13729, 5478): 1,
 (13729, 5001): 1,
 (13729, 14092): 1,
 (13729, 15990): 1,
 (13729, 11299): 1,
 (13729, 15539): 1,
 (13729, 5480): 1,
 (13729, 14650): 1,
 (13729, 16404): 1,
 (13729, 4325): 1,
 (13729, 2169): 1,
 (13729, 7423): 1,
 (13729, 2067): 1,
 (13729, 2742): 1,
 (13729, 5846): 1,
 (13729, 1008): 1,
 (13729, 11558): 1,
 (13729, 4388): 1,
 (13729, 15927): 1,
 (13729, 3304): 1,
 (13729, 14519): 1,
 (13729, 8800): 1,
 (13729, 15788): 1,
 (13729, 8889): 1,
 (13729, 4502): 1,
 (13729, 11669): 1,
 (13729, 11292): 1,
 (13729, 8050): 1,
 (13729, 15912): 1,
 (13729, 14665): 1,
 (13729, 940): 1,
 (13729, 9187): 1,
 (13729, 15984): 1,
 (13729, 1156): 1,
 (13729, 15567): 1,
 (13729, 12390): 1,
 (13729, 403): 1,
 (13729, 3793): 1,
 (13729, 14681): 1,
 (13729, 14649): 1,
 (13729, 471): 1,
 (13729, 4868): 1,
 (13729, 6943): 1,
 (13729, 13222): 1,
 (13729, 15157): 1,
 (13729, 11815): 1,
 (13729, 9753): 1,
 (13729, 261): 1,
 (13729, 9661): 1,
 (13729, 3752): 1,
 (13729, 15252): 1,
 (13729, 11726): 1,
 (13729, 3897): 1,
 (13729, 15240): 1,
 (13729, 12810): 1,
 (13729, 3705): 1,
 (13729, 12669): 1,
 (13729, 5457): 1,
 (13729, 94): 1,
 (13729, 15594): 1,
 (13729, 12581): 1,
 (13729, 8873): 1,
 (13729, 4705): 1,
 (13729, 11251): 1,
 (13729, 1441): 1,
 (13729, 16109): 1,
 (13729, 6503): 1,
 (13729, 12054): 1,
 (13729, 2713): 1,
 (13729, 479): 1,
 (13109, 12153): 1,
 (7325, 5845): 1,
 (7325, 6232): 1,
 (7325, 16354): 1,
 (7325, 14411): 1,
 (7325, 8640): 1,
 (7325, 1914): 1,
 (7325, 7340): 1,
 (7325, 11281): 1,
 (7325, 9022): 1,
 (7325, 12468): 1,
 (7325, 4437): 1,
 (7325, 3926): 1,
 (7325, 10864): 1,
 (7325, 16310): 1,
 (7325, 8384): 1,
 (7325, 7085): 1,
 (7325, 16): 1,
 (7325, 16254): 1,
 (7325, 13366): 1,
 (7325, 8280): 1,
 (7325, 13346): 1,
 (7325, 13997): 1,
 (7325, 10131): 1,
 (7325, 1701): 1,
 (7325, 3273): 1,
 (7325, 10413): 1,
 (7325, 14707): 1,
 (7325, 5013): 1,
 (7325, 14289): 1,
 (7325, 6961): 1,
 (7325, 7454): 1,
 (7325, 11169): 1,
 (7325, 9155): 1,
 (7325, 13116): 1,
 (7325, 8994): 1,
 (7325, 7974): 1,
 (7325, 5342): 1,
 (7325, 14103): 1,
 (7325, 8055): 1,
 (7325, 4701): 1,
 (7325, 946): 1,
 ...}

In [75]:
def calculate_intra_list_diversity(user_recommendations, item_similarity):
    """
    Рассчитывает разнообразие рекомендаций для одного пользователя
    """
    n = len(user_recommendations)
    if n < 2:
        return 1.0  # максимальное разнообразие для одного элемента
    
    total = 0
    count = 0
    for i in range(n):
        for j in range(i+1, n):
            item_i = user_recommendations[i]
            item_j = user_recommendations[j]
            total += 1 - item_sim_flag.get((item_i, item_j), 0)
            count += 1
    
    return total / count if count > 0 else 1.0

# Пример расчета для одного пользователя


# Пример использования
catalog_size = df['item_id'].nunique()  # в реальности может быть больше

for x in [most_pop_data, random_data, novel_recs_data]:
    user_id = x.user_id.sample(n=1).values[0]
    user_recommendations = x[x['user_id'] == user_id]['item_id'].tolist()
    diversity_score = calculate_intra_list_diversity(user_recommendations, item_sim_flag)
    print(f"Intra-list diversity for user 1: {diversity_score:.4f}")

Intra-list diversity for user 1: 0.9556
Intra-list diversity for user 1: 1.0000
Intra-list diversity for user 1: 1.0000

In [76]:
def calculate_inter_list_diversity(recommendations, max_count = 100):
    """
    Рассчитывает разнообразие рекомендаций между пользователями
    """
    user_recs = recommendations.groupby('user_id')['item_id'].apply(list).reset_index()
    rec_lists = user_recs['item_id'].tolist()
    
    if len(rec_lists) < 2:
        return 1.0
    
    total = 0
    count = 0
    for i in range(len(rec_lists)):
        for j in range(i+1, len(rec_lists)):
            set_i = set(rec_lists[i])
            set_j = set(rec_lists[j])
            intersection = len(set_i & set_j)
            union = len(set_i | set_j)
            jaccard_sim = intersection / union if union > 0 else 0
            total += 1 - jaccard_sim
            count += 1
    
    return total / count if count > 0 else 1.0

# Пример расчета
for x in [most_pop_data, random_data, novel_recs_data]:
    inter_diversity_score = calculate_inter_list_diversity(x)
    print(f"Inter-list diversity: {inter_diversity_score:.4f}")

Inter-list diversity: 0.0000
Inter-list diversity: 0.9765
Inter-list diversity: 0.0000